name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: mlugg/setup-zig@v1
      - run: sudo apt install -y glslc libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libvulkan-dev libgl-dev
      - run: zig build
